cloud:
  aws:
    credentials:
      access-key: AKIA47CRVWFDWHVR3WHQ
      secret-key: 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
    region:
      static: us-east-1
    s3:
      access:
        enable: false
      bucket: firefoxshimano
    stack:
      auto: false
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
kafka:
  enable: true

server:
  port: 8080
spring:
  application:
    name: customer
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Sports@123
    url: jdbc:mysql://localhost:3306/ecommdb?useSSL=false&serverTimezone=UTC
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: my-group-id
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  config:
    import:
      - "application_qa.yml"
      - "application_prod.yml"
  profiles:
    active:
      - "prod"


build:
  version: "1.0"

customer:
  message: "Welcome to customer related local APIs "
  contactDetails:
    name: "John Doe - Developer"
    email: "john@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345