server:
  port: 8080
logging:
  pattern:
    console : ${LOGPATTERN_CONSOLE:%green(%d{YYYY-MM-dd HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}
spring:
  application:
    name: ${SPRING_APP_NAME:customer}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Sports@123
    url: jdbc:mysql://localhost:3306/ecommdb?useSSL=false&serverTimezone=UTC
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: my-group-id
    producer:
      enabled: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  config:
    import:
      - "application_qa.yml"
      - "application_prod.yml"
  profiles:
    active:
      - "prod"
  security:
    user:
      name: ${SECURITY_USERNAME:brainstorm}
      password: ${SECURITY_PASSWORD:12345}

eureka:
  client:
    enabled: true
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname:
      preferIpAddress : true

cloud:
  aws:
    credentials:
      access-key: AKIA47CRVWFDWHVR3WHQ
      secret-key: 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
    region:
      static: us-east-1
    s3:
      access:
        enable: false
      bucket: firefoxshimano
    stack:
      auto: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: "customer"
    description: "Brainstorm ecomm customer Application"
    version: "1.0.0"

build:
  version: "1.0"

customer:
  message: "Welcome to customer related local APIs "
  contactDetails:
    name: "John Doe - Developer"
    email: "john@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345

