server:
  port: 8081
spring:
  application:
    name: ecomOrder
  datasource:
    username: root
    password: Sports@123
    url: jdbc:mysql://localhost:3306/ecommdb?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connectionTimeout: 30000
      leakDetectionThreshold: 30000
      minimumIdle: 2
      maximumPoolSize: 30
      idleTimeout: 120000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: orders_group

    producer:
      enabled: false
  config:
    import:
      - "application_qa.yml"
      - "application_prod.yml"
  profiles:
    active:
      - "prod"
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
eureka:
  client:
    enabled: true
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname:
      preferIpAddress: true

resilience4j:
  circuitbreaker:
    instances:
      customerService:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10000  # time in milliseconds
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true
saga:
  enabled: true

info:
  app:
    name: "order"
    description: "Brainstorm ecomm order Application"
    version: "2.0.0"


build:
  version: "2.0"

order:
  message: "Welcome to order related local APIs "
  contactDetails:
    name: "John Doe - Developer"
    email: "john@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345