server:
  port: 8085

spring:
  application:
    name: api-gateway

  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
      fetch-registry: true
      register-with-eureka: true

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Enables dynamic routing using Eureka
          lowerCaseServiceId: true
      routes:
        - id: order-service
          uri: lb://ECOMORDER  # Service name displays in Eureka server
          predicates:
            - Path=/api/orders/**
        - id: customer-service
          uri: lb://CUSTOMER  # Service name displays in Eureka server
          predicates:
            - Path=/api/customers/**
        - id: product-service
          uri: lb://PRODUCT  # Service name displays in Eureka server
          predicates:
            - Path=/api/products/**
