build:
  version: "3.1"

order:
  message: "Welcome to product related QA APIs "
  contactDetails:
    name: "Ram Dev - Developer"
    email: "RamDev@brainstorm.com"
  onCallSupport:
    - (222) 555-3456
    - (222) 523-3567