server:
  port: 8096
spring:
  application:
    name: stock
  datasource:
    username: root
    password: Sports@123
    url: jdbc:mysql://localhost:3306/ecommdb?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connectionTimeout: 30000
      leakDetectionThreshold: 30000
      minimumIdle: 2
      maximumPoolSize: 30
      idleTimeout: 120000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: stocks_group,reverse_stocks_group

    producer:
      enabled: false
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
eureka:
  client:
    enabled: true
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname:
      preferIpAddress: true

resilience4j:
  circuitbreaker:
    instances:
      customerService:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10000  # time in milliseconds
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true
saga:
  enabled: true
